### ISSUE TITLE
capacities

### ISSUE THREAD

**Issue by dongkun211** [vikas9087/Bilevel-Optimization-Emissions#1]
What does this part mean

**Comment by vikas9087** [comment]
Hi,

This is list of maximum percentage of supply available of each fuel type. For example, capacities = [.50, .60, .20] means that 50% of total electricity demand of customer can be satisfied using coal and similarly 60% by natural gas and so on.

I hope this clarifies now.

Vikas

**Comment by dongkun211** [comment]
Your help is greatly appreciated
